name: CI
on:
  push:
    paths:
      - src/**
      - tests/**
      - .github/workflows/ci.yml

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: Super-Linter
        uses: super-linter/super-linter@v7.3.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_CSHARP: true
          VALIDATE_DOCKERFILE_HADOLINT: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_GITLEAKS: true
  build-csharp:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4.3.0
        with:
          dotnet-version: 9.0.x
      - name: Cache
        uses: actions/cache@v4.2.2
        id: cache
        with:
          path: |
            ~/.nuget/packages
            **/obj
          key: dotnet-${{ hashFiles('**/*.csproj') }}

      - name: Setup Nuget Feeds
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          dotnet nuget add source ${{ secrets.HANGFIRE_PRO_URL }} -n hangfire-pro -u ${{ secrets.HANGFIRE_PRO_USER }} -p ${{ secrets.HANGFIRE_PRO_TOKEN }} --store-password-in-clear-text
          dotnet nuget add source ${{ secrets.HANGFIRE_ACE_URL }} -n hangfire-ace -u ${{ secrets.HANGFIRE_ACE_USER }} -p ${{ secrets.HANGFIRE_ACE_TOKEN }} --store-password-in-clear-text
          dotnet nuget add source https://nuget.pkg.github.com/SaveApis/index.json -n github -u ${{ github.actor }} -p ${{ github.token }} --store-password-in-clear-text
      - name: Restore
        if: steps.cache.outputs.cache-hit != 'true'
        run: dotnet restore src/Backend/Backend.csproj
      - name: Build
        run: dotnet build src/Backend/Backend.csproj --configuration Release --no-restore --nologo